In [16]:
# standard imports
import numpy as np
import pandas as pd


In [17]:
df = pd.read_excel("Statistical Analysis Base Data train1.xlsx")

df.columns

Index(['Weekday (Mon = 1; Sun = 7)', 'Date', 'Public Holiday?', 'Avg. Temp',
       'Precipitation', 'Sunshine Hours', 'Max. Wind (km/h)', 'Food sales'],
      dtype='object')

In [18]:
#split into x/y
x = df.drop("Food sales", axis=1) 
y = df["Food sales"]


In [19]:
# turn the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Public Holiday?"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", 
                                   one_hot,
                                   categorical_features)],
                                   remainder="passthrough")

transformed_x = transformer.fit_transform(x)
transformed_x

array([[ 1. ,  0. ,  2. , ...,  0. , 12.3, 24. ],
       [ 1. ,  0. ,  3. , ...,  0. ,  8. , 44. ],
       [ 1. ,  0. ,  4. , ...,  0. , 12.2, 42. ],
       ...,
       [ 1. ,  0. ,  5. , ...,  0. ,  2.3,  0. ],
       [ 1. ,  0. ,  6. , ...,  0. ,  8.7, 18. ],
       [ 1. ,  0. ,  7. , ...,  0. ,  2.5, 30. ]])

In [20]:
# split data into training and test sets

np.random.seed(42)
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(transformed_x, 
                                                    y, 
                                                    test_size=0.2)

In [7]:
# build a machine learning model
from sklearn.ensemble import RandomForestRegressor 

model = RandomForestRegressor()


model.fit(x_train, y_train)


RandomForestRegressor()

In [8]:
model.score(x_test, y_test) # R^2 of the prediction)

0.7588799673176236

In [9]:
# making predictions
y_preds = model.predict(x_test)


In [10]:
# prediction
y_preds[:10]

array([ 578.454,  659.608, 1388.709,  785.186,  286.817, 1342.62 ,
        942.447,  783.498, 1279.836, 1019.716])

In [11]:
# truth
np.array(y_test[:10])

array([ 609.8,  686.2, 1387.8,  650.8,  853.6, 1293.8,  700.6,  526.4,
       1609.1, 1382.9])

In [12]:
# comparing prediction to the truth
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_preds)

176.6131451612904

In [13]:
# saving the train machine learning model
# import pickle

# pickle.dump(model, open("PYTHON PROJECT", "wb"))

In [14]:
# loading a saved model
# loaded_pickle_model = pickle.load(open("PYTHON PROJECT", "rb"))

In [15]:
# making predictions
# pickle_y_preds = loaded_pickle_model.predict(x_test)

# comparing prediction to the truth
# from sklearn.metrics import mean_absolute_error
# mean_absolute_error(y_test, pickle_y_preds)


176.6131451612904