At the start of the project i had to first clean the data for suitable predictions. I used Anaconda with a Jupyter notebook for the environment.

After identifying the problem as a Supervised learning problem under Regression, I used two regression models.
RidgeRegression and RandomForestRegression. 
For the RidgeRegression model the r2 or coefficient of determination came out as 0.5938886113707722 = 0.59 .
On the otherhand, the RandomForestRegression model came out better with the r2 being 0.739210756607491 = 0.74 .

As a result of this i chose to improve the RandomRegression model.
Inorder to improve the model, I had to tune the hyperparameters of the model using RandomSeachCV but that did not work. 

Hence I resolved to using other techniques namely Correlation Analysis and Forward/Backward Attribute Selection.
This involved training the model on all the attributes or columns and slowly taking away columns to train the model for backward attribute selection and starting with one column and slowly building it up with more columns for forward attribute selection.

When improving the models, certain columns were exemepted because they didnot improve the model or were not needed but the important columns per the description of the project were not taken out.
5 models were built with similar code and the same Regression model (RandomForestRegression). 
The extra 4 models were obtained in addition to the baseline model as a result of removing certain columns that were not needed and adding a weekend column to the data.

In the first model(baseine model), r2 is 0.739210756607491 = 0.74

In the second model, r2 is 0.7588799673176236 = 0.76

In the third model, r2 is 0.7401433051483493 = 0.74

In the fourth model, r2 is  0.7550637660281101 = 0.76

In the last model, r2 is 0.7438368827358617 = 0.74


## RidgeRegression Model

In [61]:
# standard imports
import pandas as pd
import numpy as np

df = pd.read_excel("Statistical Analysis Base Data.xlsx")

In [62]:
#split into x/y
x = df.drop("Food sales", axis=1) 
y = df["Food sales"]
 
# turn the categories into numbers inorder to build the prediction model
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Public Holiday?"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", 
                                   one_hot,
                                   categorical_features)],
                                   remainder="passthrough")

transformed_x = transformer.fit_transform(x)
transformed_x


array([[ 1. ,  0. ,  2. , ...,  0. , 12.3, 24. ],
       [ 1. ,  0. ,  3. , ...,  0. ,  8. , 44. ],
       [ 1. ,  0. ,  4. , ...,  0. , 12.2, 42. ],
       ...,
       [ 1. ,  0. ,  5. , ...,  0. ,  2.3,  0. ],
       [ 1. ,  0. ,  6. , ...,  0. ,  8.7, 18. ],
       [ 1. ,  0. ,  7. , ...,  0. ,  2.5, 30. ]])

In [63]:
# split data into training and test sets
from sklearn.model_selection import train_test_split


# setup a random seed
np.random.seed(42)
x_train, x_test, y_train, y_test = train_test_split(transformed_x, 
                                                    y, 
                                                    test_size=0.2)
# trying the Ridge Regression medel
from sklearn.linear_model import Ridge


# Instantiate Ridge model and fit the data
model = Ridge()
model.fit(x_train, y_train)

# check the score of the Ridge model on test data
model.score(x_test, y_test)



0.5938886113707722

## RandomForestRegression model (first model(baseine model))

In [64]:
# standard imports
import pandas as pd
import numpy as np
df = pd.read_excel("Statistical Analysis Base Data.xlsx")



In [65]:
#split into x/y
x = df.drop("Food sales", axis=1) 
y = df["Food sales"]


In [66]:
# turn the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Public Holiday?"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", 
                                   one_hot,
                                   categorical_features)],
                                   remainder="passthrough")

transformed_x = transformer.fit_transform(x)
transformed_x


array([[ 1. ,  0. ,  2. , ...,  0. , 12.3, 24. ],
       [ 1. ,  0. ,  3. , ...,  0. ,  8. , 44. ],
       [ 1. ,  0. ,  4. , ...,  0. , 12.2, 42. ],
       ...,
       [ 1. ,  0. ,  5. , ...,  0. ,  2.3,  0. ],
       [ 1. ,  0. ,  6. , ...,  0. ,  8.7, 18. ],
       [ 1. ,  0. ,  7. , ...,  0. ,  2.5, 30. ]])

In [67]:
# split data into training and test sets

np.random.seed(42)
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(transformed_x, 
                                                    y, 
                                                    test_size=0.2)

In [68]:
# build a machine learning model
from sklearn.ensemble import RandomForestRegressor 

model_1 = RandomForestRegressor()


model_1.fit(x_train, y_train)


RandomForestRegressor()

In [69]:
model_1.score(x_test, y_test)

0.739210756607491

In [97]:
# making predictions
y_preds = model_1.predict(x_test)

In [132]:
#y_test.head()

In [146]:
#for i in range(len(x_test)):
 #   print("x=%s, Predicted=%s" % (x_test[i], y_preds[i]))
#inverse_transformer(x_test)
print("x=%s, Predicted=%s" % (x_test[9], y_preds[9])) 


x=[1.0000e+00 0.0000e+00 7.0000e+00 4.4017e+04 2.0400e+01 2.7500e+01
 2.3200e+01 0.0000e+00 3.3000e+00 5.5000e+01], Predicted=1144.565


In [147]:
#y_test.head(20)
form = pd.DataFrame({"actual": y_test, "prediction": y_preds}) .sort_index()
form.tail(31)

actual  prediction
158   212.10    614.1476
163   785.40    695.4688
164  1019.10    917.5280
168  1197.40    908.1138
173  1152.20   1027.1050
179  2297.40   1679.1710
181   273.20    584.0570
184   526.40    750.6860
195  1714.30   1406.6300
196  2092.50   1494.2110
197  1124.60    909.0310
198  1219.70    958.1540
206  1109.00   1200.7630
210   845.80    940.0400
224  1296.50   1207.7980
226   943.80   1331.5100
230   496.80    505.4420
239   883.40    812.1170
242  1275.80   1369.5980
244  1609.10   1348.8000
251   444.80    495.4760
259  1559.60   1512.7280
274   683.90    685.3580
284  1487.70   1107.1730
286   258.30    505.2360
288   609.80    587.0060
289  1258.40   1039.6570
294   580.20    777.3610
296   610.14    922.1720
300   485.00    699.7240
305   185.00    533.5470

In [108]:
# prediction
y_preds

array([ 587.006 ,  681.178 , 1427.111 ,  776.647 ,  283.831 , 1355.715 ,
        901.378 ,  750.686 , 1348.8   , 1144.565 , 1530.211 ,  695.4688,
        777.361 ,  533.547 , 1107.173 , 1039.657 , 1391.09  ,  685.114 ,
        917.528 ,  908.1138,  830.143 , 1010.116 ,  914.27  , 1200.763 ,
       1484.439 , 1027.105 ,  783.437 , 1302.261 ,  685.358 ,  495.476 ,
        774.388 ,  949.35  , 1564.916 , 1512.728 ,  769.805 ,  835.816 ,
       1373.971 , 1282.557 ,  909.031 ,  354.501 ,  728.943 ,  370.456 ,
       1679.171 , 1369.598 ,  922.172 , 1494.211 , 1331.51  ,  693.482 ,
        505.236 ,  813.115 ,  735.029 ,  812.117 , 1050.907 ,  806.1   ,
        584.057 ,  505.442 ,  699.724 ,  958.154 , 1406.63  ,  940.04  ,
       1207.798 ,  614.1476])

In [106]:
# truth
#np.array(y)

In [49]:
# comparing prediction to the truth
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_preds)

178.56635483870977

### evaluating the model using evaluation metrics for regression model

In [15]:
# Evaluating a machine learning model
model_1.score(x_test, y_test)  # Returns the coefficient of determination R^2 of the prediction)

0.739210756607491

In [16]:
from sklearn.metrics import r2_score

# fill an arrar with y_test mean
y_test_mean = np.full(len(y_test), y_test.mean())

# predicting the mean
y_test.mean()


978.1941935483871

In [17]:
y_test_mean # this is an array full of the above values 

array([978.19419355, 978.19419355, 978.19419355, 978.19419355,
       978.19419355, 978.19419355, 978.19419355, 978.19419355,
       978.19419355, 978.19419355, 978.19419355, 978.19419355,
       978.19419355, 978.19419355, 978.19419355, 978.19419355,
       978.19419355, 978.19419355, 978.19419355, 978.19419355,
       978.19419355, 978.19419355, 978.19419355, 978.19419355,
       978.19419355, 978.19419355, 978.19419355, 978.19419355,
       978.19419355, 978.19419355, 978.19419355, 978.19419355,
       978.19419355, 978.19419355, 978.19419355, 978.19419355,
       978.19419355, 978.19419355, 978.19419355, 978.19419355,
       978.19419355, 978.19419355, 978.19419355, 978.19419355,
       978.19419355, 978.19419355, 978.19419355, 978.19419355,
       978.19419355, 978.19419355, 978.19419355, 978.19419355,
       978.19419355, 978.19419355, 978.19419355, 978.19419355,
       978.19419355, 978.19419355, 978.19419355, 978.19419355,
       978.19419355, 978.19419355])

In [18]:
r2_score(y_test, y_test_mean) # If all the model does is predict the mean of the target the R^2 value will be 0 

0.0

In [19]:
r2_score(y_test, y_test) # if model perfectly predicts a range of numbers its R^2 value will be 1

1.0

## MAE

In [20]:
# mean absolute error
from sklearn.metrics import mean_absolute_error

y_preds = model_1.predict(x_test)
mae = mean_absolute_error(y_test, y_preds)
mae


178.56635483870977

## MSE

In [21]:
# mean squared error     
# mse will always be higher than mean absolute error cause it squares the errors

from sklearn.metrics import mean_squared_error

y_preds = model_1.predict(x_test)
mse = mean_squared_error(y_test, y_preds)
mse


56215.031616687724

## Improving the model

### second model

In [148]:
df = pd.read_excel("Statistical Analysis Base Data train1.xlsx")

df.columns

Index(['Weekday (Mon = 1; Sun = 7)', 'Date', 'Public Holiday?', 'Avg. Temp',
       'Precipitation', 'Sunshine Hours', 'Max. Wind (km/h)', 'Food sales'],
      dtype='object')

In [149]:
#split into x/y
x = df.drop("Food sales", axis=1) 
y = df["Food sales"]


In [150]:
# turn the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Public Holiday?"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", 
                                   one_hot,
                                   categorical_features)],
                                   remainder="passthrough")

transformed_x = transformer.fit_transform(x)
transformed_x

array([[ 1. ,  0. ,  2. , ...,  0. , 12.3, 24. ],
       [ 1. ,  0. ,  3. , ...,  0. ,  8. , 44. ],
       [ 1. ,  0. ,  4. , ...,  0. , 12.2, 42. ],
       ...,
       [ 1. ,  0. ,  5. , ...,  0. ,  2.3,  0. ],
       [ 1. ,  0. ,  6. , ...,  0. ,  8.7, 18. ],
       [ 1. ,  0. ,  7. , ...,  0. ,  2.5, 30. ]])

In [151]:
# split data into training and test sets

np.random.seed(42)
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(transformed_x, 
                                                    y, 
                                                    test_size=0.2)

In [152]:
# build a machine learning model
from sklearn.ensemble import RandomForestRegressor 

model_2 = RandomForestRegressor()


model_2.fit(x_train, y_train)


RandomForestRegressor()

In [153]:
model_2.score(x_test, y_test)

0.7588799673176236

In [154]:
# making predictions
y_preds = model_2.predict(x_test)

In [157]:
#y_test.head(20)
form = pd.DataFrame({"actual": y_test, "prediction": y_preds}) .sort_index()
form.tail(31)

actual  prediction
158   212.10     691.085
163   785.40     737.184
164  1019.10    1073.210
168  1197.40    1027.019
173  1152.20    1180.719
179  2297.40    1651.154
181   273.20     601.041
184   526.40     783.498
195  1714.30    1524.361
196  2092.50    1638.918
197  1124.60     952.897
198  1219.70    1026.418
206  1109.00    1211.462
210   845.80     918.895
224  1296.50    1180.618
226   943.80    1198.950
230   496.80     463.059
239   883.40     828.375
242  1275.80    1322.066
244  1609.10    1279.836
251   444.80     502.173
259  1559.60    1461.366
274   683.90     735.594
284  1487.70    1102.200
286   258.30     535.360
288   609.80     578.454
289  1258.40    1023.927
294   580.20     784.730
296   610.14     922.849
300   485.00     685.675
305   185.00     541.937

In [38]:
# prediction
y_preds[:10]

array([ 578.454,  659.608, 1388.709,  785.186,  286.817, 1342.62 ,
        942.447,  783.498, 1279.836, 1019.716])

In [39]:
# truth
np.array(y_test[:10])

array([ 609.8,  686.2, 1387.8,  650.8,  853.6, 1293.8,  700.6,  526.4,
       1609.1, 1382.9])

In [28]:
# comparing prediction to the truth
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_preds)

178.56635483870977

### third model

In [158]:
df = pd.read_excel("Statistical Analysis Base Data train2.xlsx")

df.columns

Index(['Weekday (Mon = 1; Sun = 7)', 'Date', 'Public Holiday?', 'Weekend?',
       'Min. Temp', 'Max. Temp', 'Avg. Temp', 'Precipitation',
       'Sunshine Hours', 'Max. Wind (km/h)', 'Food sales'],
      dtype='object')

In [159]:
#split into x/y
x = df.drop("Food sales", axis=1) 
y = df["Food sales"]


In [160]:
# turn the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Public Holiday?", "Weekend?"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", 
                                   one_hot,
                                   categorical_features)],
                                   remainder="passthrough")

transformed_x = transformer.fit_transform(x)
transformed_x

array([[ 1. ,  0. ,  1. , ...,  0. , 12.3, 24. ],
       [ 1. ,  0. ,  1. , ...,  0. ,  8. , 44. ],
       [ 1. ,  0. ,  1. , ...,  0. , 12.2, 42. ],
       ...,
       [ 1. ,  0. ,  1. , ...,  0. ,  2.3,  0. ],
       [ 1. ,  0. ,  0. , ...,  0. ,  8.7, 18. ],
       [ 1. ,  0. ,  0. , ...,  0. ,  2.5, 30. ]])

In [161]:
# split data into training and test sets

np.random.seed(42)
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(transformed_x, 
                                                    y, 
                                                    test_size=0.2)

In [162]:
# build a machine learning model
from sklearn.ensemble import RandomForestRegressor 

model_3 = RandomForestRegressor()


model_3.fit(x_train, y_train)


RandomForestRegressor()

In [170]:
model_3.score(x_test, y_test)

0.7401433051483493

In [171]:
# making predictions
y_preds = model_3.predict(x_test)

In [175]:
#y_test.head(20)
form = pd.DataFrame({"actual": y_test, "prediction": y_preds}) .sort_index()
form.tail(31)

actual  prediction
158   212.10    617.3470
163   785.40    734.7058
164  1019.10    926.6100
168  1197.40    933.1270
173  1152.20   1049.5850
179  2297.40   1665.6790
181   273.20    593.2080
184   526.40    765.7900
195  1714.30   1420.4160
196  2092.50   1455.9550
197  1124.60    907.4790
198  1219.70    946.7170
206  1109.00   1184.1110
210   845.80    958.8040
224  1296.50   1200.0340
226   943.80   1319.3280
230   496.80    517.6450
239   883.40    795.0480
242  1275.80   1350.0410
244  1609.10   1375.6140
251   444.80    494.6710
259  1559.60   1515.7930
274   683.90    713.4000
284  1487.70   1125.6370
286   258.30    496.7930
288   609.80    602.8360
289  1258.40   1045.2490
294   580.20    775.4188
296   610.14    919.4810
300   485.00    738.4830
305   185.00    538.8610

In [172]:
# prediction
y_preds[:10]

array([ 602.836,  696.024, 1427.27 ,  775.97 ,  285.271, 1355.032,
        900.485,  765.79 , 1375.614, 1128.402])

In [169]:
# truth
np.array(y_test[:10])

array([ 609.8,  686.2, 1387.8,  650.8,  853.6, 1293.8,  700.6,  526.4,
       1609.1, 1382.9])

In [32]:
# comparing prediction to the truth
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_preds)

178.56635483870977

### fourth model


In [230]:
df = pd.read_excel("Statistical Analysis Base Data train3.xlsx")

df.columns

Index(['Weekday (Mon = 1; Sun = 7)', 'Date', 'Public Holiday?', 'Weekend?',
       'Avg. Temp', 'Precipitation', 'Sunshine Hours', 'Max. Wind (km/h)',
       'Food sales'],
      dtype='object')

In [231]:
#split into x/y
x = df.drop("Food sales", axis=1) 
y = df["Food sales"]


In [232]:
# turn the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Public Holiday?", "Weekend?"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", 
                                   one_hot,
                                   categorical_features)],
                                   remainder="passthrough")

transformed_x = transformer.fit_transform(x)
transformed_x

array([[ 1. ,  0. ,  1. , ...,  0. , 12.3, 24. ],
       [ 1. ,  0. ,  1. , ...,  0. ,  8. , 44. ],
       [ 1. ,  0. ,  1. , ...,  0. , 12.2, 42. ],
       ...,
       [ 1. ,  0. ,  1. , ...,  0. ,  2.3,  0. ],
       [ 1. ,  0. ,  0. , ...,  0. ,  8.7, 18. ],
       [ 1. ,  0. ,  0. , ...,  0. ,  2.5, 30. ]])

In [233]:
# split data into training and test sets

np.random.seed(42)
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(transformed_x, 
                                                    y, 
                                                    test_size=0.2)

In [234]:
# build a machine learning model
from sklearn.ensemble import RandomForestRegressor 

model_4 = RandomForestRegressor()


model_4.fit(x_train, y_train)


RandomForestRegressor()

In [237]:
model_4.score(x_test, y_test)

0.7550637660281101

In [242]:
#y_test.head(20)
form = pd.DataFrame({"actual": y_test, "prediction": y_preds}) .sort_index()
form.tail(31)

actual  prediction
158   212.10    701.3360
163   785.40    745.6430
164  1019.10   1066.0840
168  1197.40   1020.9280
173  1152.20   1174.0910
179  2297.40   1679.3800
181   273.20    589.0400
184   526.40    796.4030
195  1714.30   1476.2530
196  2092.50   1608.4110
197  1124.60    944.4650
198  1219.70   1020.8360
206  1109.00   1214.5160
210   845.80    923.1230
224  1296.50   1195.9050
226   943.80   1184.2480
230   496.80    459.3540
239   883.40    844.7140
242  1275.80   1358.1890
244  1609.10   1267.5340
251   444.80    510.7430
259  1559.60   1463.5550
274   683.90    779.6000
284  1487.70   1107.5370
286   258.30    516.8540
288   609.80    571.6340
289  1258.40   1025.0760
294   580.20    780.9138
296   610.14    919.1220
300   485.00    682.9560
305   185.00    533.6980

In [239]:
# making predictions
y_preds = model_4.predict(x_test)

In [240]:
# prediction
y_preds[:10]

array([ 571.634,  667.453, 1375.338,  795.042,  293.283, 1336.619,
        952.966,  796.403, 1267.534, 1008.669])

In [241]:
# truth
np.array(y_test[:10])

array([ 609.8,  686.2, 1387.8,  650.8,  853.6, 1293.8,  700.6,  526.4,
       1609.1, 1382.9])

In [197]:
# comparing prediction to the truth
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_preds)

179.21649677419364

### fifth model

In [243]:
df = pd.read_excel("Statistical Analysis Base Data train4.xlsx")

df.columns

Index(['Weekday (Mon = 1; Sun = 7)', 'Date', 'Public Holiday?', 'Weekend?',
       'Min. Temp', 'Max. Temp', 'Precipitation', 'Sunshine Hours',
       'Max. Wind (km/h)', 'Food sales'],
      dtype='object')

In [244]:
#split into x/y
x = df.drop("Food sales", axis=1) 
y = df["Food sales"]


In [245]:
# turn the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Public Holiday?", "Weekend?"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", 
                                   one_hot,
                                   categorical_features)],
                                   remainder="passthrough")

transformed_x = transformer.fit_transform(x)
transformed_x

array([[ 1. ,  0. ,  1. , ...,  0. , 12.3, 24. ],
       [ 1. ,  0. ,  1. , ...,  0. ,  8. , 44. ],
       [ 1. ,  0. ,  1. , ...,  0. , 12.2, 42. ],
       ...,
       [ 1. ,  0. ,  1. , ...,  0. ,  2.3,  0. ],
       [ 1. ,  0. ,  0. , ...,  0. ,  8.7, 18. ],
       [ 1. ,  0. ,  0. , ...,  0. ,  2.5, 30. ]])

In [246]:
# split data into training and test sets

np.random.seed(42)
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(transformed_x, 
                                                    y, 
                                                    test_size=0.2)

In [247]:
# build a machine learning model
from sklearn.ensemble import RandomForestRegressor 

model_5 = RandomForestRegressor()


model_5.fit(x_train, y_train)


RandomForestRegressor()

In [252]:
model_5.score(x_test, y_test)

0.7438368827358617

In [253]:
# making predictions
y_preds = model_5.predict(x_test)

In [254]:
#y_test.head(20)
form = pd.DataFrame({"actual": y_test, "prediction": y_preds}) .sort_index()
form.tail(31)

actual  prediction
158   212.10    635.7828
163   785.40    695.1520
164  1019.10    873.5510
168  1197.40    932.8080
173  1152.20   1025.2830
179  2297.40   1678.6250
181   273.20    612.1760
184   526.40    758.2770
195  1714.30   1420.2580
196  2092.50   1471.1950
197  1124.60    898.8900
198  1219.70    938.3740
206  1109.00   1212.4400
210   845.80    934.9970
224  1296.50   1236.2100
226   943.80   1325.0020
230   496.80    515.5680
239   883.40    789.9020
242  1275.80   1368.7690
244  1609.10   1382.8770
251   444.80    517.6820
259  1559.60   1506.7210
274   683.90    692.3210
284  1487.70   1139.8870
286   258.30    477.2010
288   609.80    599.9280
289  1258.40   1071.0420
294   580.20    765.7810
296   610.14    924.4760
300   485.00    711.2040
305   185.00    533.2880

In [255]:
# prediction
y_preds[:10]

array([ 599.928,  648.33 , 1428.801,  786.836,  301.468, 1364.957,
        887.444,  758.277, 1382.877, 1144.171])

In [228]:
# truth
np.array(y_test[:10])

array([ 609.8,  686.2, 1387.8,  650.8,  853.6, 1293.8,  700.6,  526.4,
       1609.1, 1382.9])

In [219]:
# comparing prediction to the truth
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_preds)

179.77938387096776

## Saving and loading the trained prediction models

In [214]:
# import pickle
# save an existing model to a file

# pickle.dump(model, open(" with_ridge_regression_model.pkl", "wb"))


In [215]:
# pickle.dump(model_1, open("baseline_random_forest_regression_model", "wb"))
# pickle.dump(model_2, open("train_1_rfrm _highest_r^2", "wb"))
# pickle.dump(model_3, open("train_2_rfrm", "wb"))
# pickle.dump(model_4, open("train_3_rfrm", "wb"))
# pickle.dump(model_5, open("train_4_rfrm", "wb"))
